* v1.1 "Inky Hand"
** v1.1.00
*** Users

- Adds a simple and powerful user interface exposing every aspect of Org2Blog—many of which you may never have known even existed before.
  - Use the one-keypress help menu to look up the documentation behind every menu entry along with the function name behind it if you want to bind it to a key.
- Includes the manual built-in to the application. It is the README.org so you don't have to go to the web page to read it.
- Expands on and revises every aspect of documentation including explanations and screenshots.
  - Blogging styles and strategies covered range from first-time blogging to advanced use with multiple blogs and diverse workflows.
- Adds an API for automating bulk import of Org files when you want to move from another Org based blogging platform to Org2Blog.
- Added a new logo:
  - A WordPress operator's inky hand, colored by Org mode, cradles a special press plate for Org2Blog: Org2Blog's first logo. Thank you Cari at [[http://sepiarainbow.com/][Sepia Rainbow Designs]] for this brilliant logo.
- Adds a built-in README with links to learn more about this project, how to start having fun blogging, and even how Free Software is critical to you as a user and society as a whole.

*** Developers

- Now requires at least Emacs 26.3 and Org mode 9.1.9.
- Expanded and revised every aspect of documentation including running from the source code instead of a package and debugging various network issues.
- Adds steps for rebuilding the readme
- Revises contribution expectations
- Adds scripted system integration testing covering 50% of Org2Blog's functionality
- Imports ~metaweblog~
- Adds ~org2blog-def-update-artifacts~ to update version numbers across all package files. See ~org2blog-def--package~ for details.
- Names refactored to standardize language.
- All code brought up to GNU and MELPA coding and packaging standards.

*** Maintainers

- Adds steps for all aspects of package maintenance
- Adds function deprecations for future future retirement
- Blog ID will only ever be 1: Org2Blog doesn't support multi-site installs. See ~org2blog--default-blogid~.

*** Fixes

- ~ox-wp~ exporter includes source block IDs.
- Completed and corrected implementation of various functionality.

** v1.1.01-v1.1.12

- v1.1.01
  - Standardized version numbers across Org2Blog, OX-WP, and MetaWeblog to 1.1.1
- v1.1.02
  - Load =subr-x=.
- v1.1.03
  - Correct listing format spacing in ~ox-wp-src-block-shortcode~ and ~ox-wp-src-block-html~.
- v1.1.04
  - Remove "Listing" prefix ~ox-wp-src-block-shortcode~ and ~ox-wp-src-block-html~.
- v1.1.05
  - Make Subtree Entries using a template like Buffer Entries already do.
- v1.1.06
  - Give Tags configurable default values like Categories already do.
- v1.1.07
  - Refactor Image Uploading Functionality
    - No longer uploads =A HREF= links.
    - Now an Option disabled by default.
    - Expanded documentation.
- v1.1.08
  - Completely disabled publishing so re-enabled it.
- v1.1.09
  - Implement `Excerpt' property
- v1.1.10
  - Restore narrowing functionality when posting buffer entries.
  - Corrected title creation bug exposed by restoring narrowing.
- v1.1.11
  - Raw HTML support with ~wp~ snippets and blocks for more straightforward custom HTML.
  - Narrowing approach to store multiple posts in a single file makes exporting to other formats easier.
  - Improved Contribution Expectations for Documentation and Coding style makes contributing easier.
  - Added Issue template, Bug report template, and Pull request template for easier creation and resolution.
  - Unfilled documentation making grammar enabling the use of checking tools for more straightforward grammar checking.
  - Structure templates for inserting RAW HTML using snippets or blocks.
  - Minor refactorings to ease maintenance.
  - Added testimonials for the fun of it.
  - After this release, only bug fixes: new development in v1.2.0 branch starting with migration to the latest Emacs and Org mode.
- v1.1.12
  - Correctly use and document autoloads
  - Don't populate kill ring with version message
  - Documentation cleanup

** v1.1.13-

- v1.1.13
  - Emacs v27.1 🠆 v28.1
  - Org v9.1.9 🠆 9.5.2
  - HTMLize v1.54 🠆 v1.56
  - XML-RPC v1.6.12 🠆 1.6.15
  - Convert system definition from hashtables to structs
  - Load categories, tags, and pages without failing on error
  - Add tag checkout to org2blog-def-checkout-statement
  - Document WordPress version

* v1.0
** v1.0.00

Communicate completeness of the library with a first major release.

** v1.0.01

Use latest metaweblog

** v1.0.02

Increment for new metaweblog version.

** v1.0.03

Adds Hydra support for user-interface.

* v0.9
** v0.9.01

Bump up version to 0.9.1.

** v0.9.02

Bump up version.

** v0.9.03

- v0.9.2 ad389ae was released on 14-12-14
- Development continued until 16-05-02 fc7b2d9
- Today is 17-05-19
  - It has been in use for one year and seventeen days
- And today
  - Merged post subtree and publish and it is fine
  - Added dependency on Org-Mode 8.3
- So therefore a new release
  - v0.9.3

