* Miscellaneous

1. You may want to look at the [[http://orgmode.org/manual/Export-options.html#Export-options][Export options]] and [[http://orgmode.org/manual/HTML-export.html#HTML-export][HTML export]]
   sections of the org-manual.

2. If you wish to post to blogger from org-mode, look at -

   1. org2blog/atom, a g-client extension by [[http://tehom-blog.blogspot.com/][Tom Breton]]

   2. [[http://github.com/rileyrg/org-googlecl][org-googlecl]] by Richard Riley -- uses [[http://code.google.com/p/googlecl/][googlecl]]

3. Please go through the README and the FAQ, before writing to me.
   Also, looking at =M-x customize-group org2blog-wp= might help.

4. If you have an issue/bug/feature request, use the issue tracker
   on git or drop a mail to punchagan+org2blog[at]gmail[dot]com.
   I'd also appreciate patches/suggestions to improve the
   documentation.  Feel free to drop in with general comments, too.
   I'd love to hear from you!  NOTE: If you are using the package
   from ELPA, please try using the latest =git= version
   before filing a bug report.

5. Feel free to add your site to the list of sites using org2blog,
   on the [[https://github.com/punchagan/org2blog/wiki/Blogs-using-org2blog][wiki]] at github.

