* Overview
  org2blog is a tool to publish directly from Emacs' org-mode to
  [[http://wordpress.org/][WordPress]] blogs.  

  It is inspired by and based on a [[http://paste.lisp.org/display/69993][wordpress posting client for
  muse-mode]] written by [[http://www.emacswiki.org/emacs/AshishShukla][Ashish Shukla]].  

  org2blog is licensed under GPLv3

* Installation

  Download org2blog from github

  : git clone http://github.com/punchagan/org2blog.git
  
  Add the org2blog directory to your load path and then add

  : (require 'org2blog)

  to your dot emacs.  

  *org2blog depends on xml-rpc available at [[http://launchpad.net/xml-rpc-el][Launchpad]].  Add it to your
  load-path before using org2blog.*

  You can optionally save the xmlrpc url of your blog and the username.

  : (setq org2blog-server-url "http://username.wordpress.com/xmlrpc.php"
  :       org2blog-server-user "username"
  :       org2blog-server-weblog-id "")

  If you use only categories, set the org2blog-use-tags-as-categories
  variable. 

  : (setq org2blog-use-tags-as-categories t)

  If you wish to be asked for confirmation before publishing a post,
  set the variable =org2blog-confirm-post=. 

  To browse or customize other variables use the customize group
  function.

  : M-x customize-group org2blog RET
  
  

* Usage
  1. Log in using *M-x org2blog-login*.  Provide xmlrpc url, username,
     password and blog-id. (blog-id isn't really being used.)
     Optionally, you could set these in your .emacs.    
     
  2. To start writing a new post use *M-x org2blog-new-entry*. 
     - Tags and Categories are comma or space separated values.
       Completion (for both) is triggered using *C-c t*.  If a new
       category is used you will be prompted before adding it.  
     - The excerpt for a post can be written as =#+DESCRIPTION=.  
     - The parent for a page can be specified using =#+PARENT=.  *C-c
       t* again provides completion for the page name. 

  3. If you wish to
     - post buffer as draft - *M-x org2blog-post-buffer* or *C-c d* 
     - to publish buffer - *C-u M-x org2blog-post-buffer* or *C-c p* 
     - to post buffer as page draft - *M-x
       org2blog-post-buffer-as-page*  or *C-c D* 
     - to publish buffer as page - *C-u M-x
       org2blog-post-buffer-as-page*  or *C-c P*

  4. You can post your existing org-files too. 
      - Add =#+TITLE=, =#+OPTIONS=, =#+TAGS=, =#+CATEGORY=,
        =#+DESCRIPTION=, =#+DATE=, to your file.  (All of these are
        Optional)
      - If you wish to edit an existing post, add a =#+POSTID=.
      - Post buffer using the function names, as above. 
      - Alternatively, you could enable org2blog-mode using *M-x
        org2blog-mode*.  This provides the key-bindings *C-c p*, *C-c
        d* and *C-c t*. 

  5. You can also post a subtree, with *M-x
     org2blog-post-subtree*. Tags of the subtree will be used for 
     tags. Other properties can be set using a property drawer. 

  6. To delete an entry or a page -
     - If you are in the buffer of the entry/page, with =#+POSTID=
       present on the page, use *M-x org2blog-delete-entry* or *M-x
       org2blog-delete-page*  
     - If you want to delete a particular post (whose post-id is
       known) from any buffer, use *C-u post-id M-x
       org2blog-delete-entry*. Similarly, for a page. 

* Miscellaneous 
  1. You may want to look at the [[http://orgmode.org/manual/Export-options.html#Export-options][Export options]] and [[http://orgmode.org/manual/HTML-export.html#HTML-export][HTML export]]
     sections of the org-manual.

  2. If you wish to post to blogger from org-mode, look at the
     [[http://code.google.com/p/emacspeak/source/browse/trunk/lisp/g-client/org2blogger.el][g-client extension]] by [[http://en.wikipedia.org/wiki/T._V._Raman][T. V. Raman]].  

  3. If you have an issue/bug/feature request, use the issue tracker
     on git or drop a mail to punchagan+org2blog[at]gmail[dot]com.  

  4. If you haven't found a bug/issue, but have tried out and/or are
     using org2blog to post to your blog, post me a line on how you
     use it and on what blog. I'd love to hear from you!
     
